"""Advisory output representation.

Authority: layer3-prototype-specification.md §6.
"""
from __future__ import annotations

import dataclasses


@dataclasses.dataclass(frozen=True)
class Advisory:
    """One advisory output generated by a fired Layer 3 rule.

    Invariants (guaranteed by construction in the engine):
      - type ∈ A_AI(S) for the governing state — because the engine fires only rules
        in the validated RS(S) and ConclusionTypes(RS(S)) ⊆ A_AI(S) was verified by
        validate_rule_set() before reasoning began.
      - rule_id references an actually fired rule — no advisory exists without a fired rule.

    Human-authority boundary:
      - A Go advisory is NOT a departure approval.
      - A Delay advisory is NOT a prohibition.
      - No field encodes approval, prohibition, override, or automated decision.
      - An empty advisory list is not equivalent to a prohibition.

    Note: payload is a mutable dict; Advisory objects are not hashable.
    """

    type: str         # ∈ R = {"Go","Delay","DepartureTime","Duration"}; also ∈ A_AI(S)
    payload: dict     # type-specific content; "reason" key is supported at Batch 2 closure
    rule_id: str      # rule in RS(S) that fired and produced this advisory
    explanation: str  # human-readable rationale text derived from payload["reason"]
