#!/usr/bin/env python3
import csv, json, hashlib, pathlib, io, collections
import pandas as pd
HERE=pathlib.Path(__file__).resolve().parent
F=["id","file","locator","claim","configuration_scope","classification","canonical_authority","action","status","notes"]
rows=[
 ("RF-01","docs/canonical/empirical-findings-2026-09-06.md","F-14 heading","Q6 RESOLVED: wave resolution matters. The headline drops to 8.3%","v2 sea wind + MFWAM at the 1.9 m wave threshold","ACTIVE-CANONICAL-DRIFT","0a generated by canonical_figures.py","Heading changed to 'wave-model resolution materially changes the measured Level 2 rate'; F-14 ID preserved","REPAIRED","8.3% superseded twice - by the 1.9 to 1.25 m amendment, then by SDR-001. A heading asserting a headline figure governs the whole section"),
 ("RF-02","docs/canonical/empirical-findings-2026-09-06.md","F-14 'Which figure to report'","The defensible presentation is both: the MFWAM figure as primary, ERA5 alongside it","2026-09-06 reasoning, pre-option-C","ACTIVE-CANONICAL-DRIFT","0a: PRIMARY = ERA5 5-yr 5.81%; RESOLUTION = MFWAM 4.48%","Retained as the reasoning of the day, with a banner giving the canonical contract and the opposite role assignment","REPAIRED","THE CORE RESIDUE, and it INVERTS the canonical roles: this finding proposed MFWAM as primary on siting; option C made ERA5 primary on record length. The dual-configuration idea survived, the assignment did not"),
 ("RF-03","docs/canonical/empirical-findings-2026-09-06.md","F-14 supersession note","The primary figure is now 6.1% - see 0a","post-1.9-to-1.25, pre-SDR-001","ACTIVE-CANONICAL-DRIFT","0a: 5.81% / 4.48%","Corrected; full evolution 12.4 -> 8.3 -> 6.1 -> 5.81/4.48 stated","REPAIRED","A supersession note that itself named a superseded primary - it pointed to 0a while contradicting it"),
 ("RF-04","docs/canonical/empirical-findings-2026-09-06.md","F-14 closing note","under MFWAM small-vessel UNSAFE via wave height never occurs (max 1.84 m against a 1.9 m threshold)","1.9 m wave threshold","ACTIVE-CANONICAL-DRIFT","canonical small-vessel UNSAFE boundary 1.25 m","Scoped to the 1.9 m boundary; canonical counts added","REPAIRED","Verified: at the canonical 1.25 m, MFWAM exceeds in 937 hours and ERA5 in 2,516 - wave-driven UNSAFE IS reachable. Like F-13's margin, the near-miss closed by moving the threshold, not the data"),
 ("RF-05","docs/canonical/empirical-findings-2026-09-06.md","F-15 divergence table note","PRIMARY configuration ... RESOLUTION gives the same structure with Level 2 at 5.98%. Updated 2026-09-08","pre-SDR-001, superseded fixed-clock g_t","ACTIVE-CANONICAL-DRIFT","condition_comparison.py: 42.88 / 48.69 / 5.81 / 4.48 over 9,135 hours","PRE-SDR-001 banner added with canonical values; original note retained beneath","REPAIRED","'Updated 2026-09-08' made it read as current when it predates the same day's migration"),
 ("RF-06","docs/canonical/empirical-findings-2026-09-06.md","F-15 Level decomposition","C0-C1 = 24.64%; C0-C2 = 32.36%; difference = 7.72% attributable to Level 2 alone","pre-SDR-001","ACTIVE-CANONICAL-DRIFT","condition_comparison.py","Marked pre-SDR-001 with canonical values inline; the isolation METHOD noted as unchanged","REPAIRED","The method survives; only the numbers moved"),
 ("RF-07","docs/canonical/empirical-findings-2026-09-06.md","F-15 C3 = C1 result","C3 = C1, divergence 0.00%","structural - configuration-independent","ACTIVE-CORRECT","canonical_figures.py and condition_comparison.py: 0.00% in both configs","NO EDIT - explicitly reinforced","VERIFIED","A property of the classification-to-admissible-set mapping, not of the data. No threshold, wave model or g_t change can move it - which is why it answers the novelty objection"),
 ("RF-08","docs/canonical/empirical-findings-2026-09-06.md","F-16 Effect paragraph","Level 2 binding 7.84 -> 7.72 (primary), 6.15 -> 5.98 (resolution); daylight UNSAFE 1,170; weather-driven 11.8%","immediately post-rainfall-amendment, pre-SDR-001","ACTIVE-CANONICAL-DRIFT","0a","Marked as intermediate state with canonical values; the finding's conclusion retained","REPAIRED","Read as the resulting current figures. The conclusion - the amendment moved only CAUTION, UNSAFE untouched - holds unchanged"),
 ("RF-09","docs/canonical/empirical-findings-2026-09-06.md","0a Predecessors table","12.4% / 8.3% / 6.1% / 7.84% / 6.15% / 10.7% etc under 'do not report these'","each row names its configuration","ACTIVE-CORRECT","-","NO EDIT","Already the correct pattern: historical figures retained with explicit scope under an explicit do-not-report heading"),
 ("RF-10","docs/canonical/empirical-findings-2026-09-06.md","0a regeneration banner","Previous canonical figures under the superseded fixed-clock g_t ... no longer current","pre-SDR-001","ACTIVE-CORRECT","-","NO EDIT","Correctly scoped"),
 ("RF-11","docs/canonical/empirical-findings-2026-09-06.md","0a headline guidance","PRIMARY is the headline because it covers the full five years; RESOLUTION is the check","canonical","ACTIVE-CORRECT","canonical_figures.py","NO EDIT","This is the current reporting contract that F-14 contradicted"),
 ("RF-12","docs/canonical/empirical-findings-2026-09-06.md","0b method note","0a listed 6.1% beside 97.5% and 10.7% as though one analysis produced all three","historical narrative","HISTORICAL-SUPERSEDED","-","NO EDIT","A record of the error, not an instruction"),
 ("RF-13","docs/canonical/finding-met-lower-boundary-gap.md","Empirical consequence","7.84 to 7.72; 6.15 to 5.98","pre-SDR-001","HISTORICAL-SUPERSEDED","-","NO EDIT","Dated finding document narrating the amendment's immediate effect; scoped by context"),
 ("RF-14","docs/canonical/appendix-c-formalisation.md","g_r amendment note","Level 2 binding falls from 7.84% to 7.72%","pre-SDR-001","HISTORICAL-SUPERSEDED","-","NO EDIT","Appendix C is protected; the note is scoped to the amendment it describes"),
 ("RF-15","CLAUDE.md","g_t section","7.72% / 5.98% were computed under the superseded classifier and are provenance only","canonical","ACTIVE-CORRECT","-","NO EDIT","Already states the supersession explicitly"),
 ("RF-16","publications/active/journal-1/*","various","reportable-figure guidance","-","DEFERRED-JOURNAL1","-","RECORDED, NOT FIXED","Out of scope for this branch"),
]
with open(HERE/"reportable-figure-residue-audit.csv","w",newline="",encoding="utf-8") as fh:
    w=csv.DictWriter(fh,fieldnames=F,quoting=csv.QUOTE_MINIMAL); w.writeheader()
    for r in rows: w.writerow(dict(zip(F,r)))
ver={
 "section_0a_vs_executable":{"level2_PRIMARY":"5.81%","level2_RESOLUTION":"4.48%",
   "daylight_unsafe":"1262 / 455","g_o":"98.71% / 97.66%","g_t":"86.82% / 90.19%",
   "g_r_daylight":"1.48% / 2.70%","g_r_all_hours":"0.20% / 0.26%",
   "C1_C3":"0.00% / 0.00%","C0_C1":"42.88%","C0_C2":"48.69%",
   "agreement":"section 0a matches canonical_figures.py and condition_comparison.py exactly"},
 "reporting_contract":{"PRIMARY":"5.81% - 5.00 yr ERA5-Ocean ~50 km - HEADLINE",
   "RESOLUTION":"4.48% - 3.25 yr MFWAM ~8 km - SENSITIVITY CHECK",
   "note":"F-14 proposed the inverse assignment (MFWAM primary on siting); option C chose ERA5 on record length"},
 "figure_evolution":"12.4 -> 8.3 -> 6.1 -> 5.81 (PRIMARY) / 4.48 (RESOLUTION)",
 "wave_unsafe_check":{"canonical_small_UNSAFE_boundary_m":1.25,
   "MFWAM_hours_above_1_25":937,"ERA5_hours_above_1_25":2516,
   "MFWAM_hours_above_1_9":0,"ERA5_hours_above_1_9":43,
   "note":"F-14's 'never occurs' is a property of the superseded 1.9 m boundary only"},
 "structural_invariant":"C3 = C1 at exactly 0.00% in both configurations, before and after migration",
 "active_stale_reportable_instructions":0,
 "empirical":{"level2":"5.81% / 4.48%","g_o":"98.71% / 97.66%","g_t":"86.82% / 90.19%",
   "g_r_daylight":"1.48% / 2.70%","g_r_all_hours":"0.20% / 0.26%","daylight_unsafe":"1262 / 455",
   "transitions":"3661 / 3439 / 222 / 26 / 10.36%"},
 "register":{"total":24,"CONFIRMED":15,"REFUTED":9,"P09":3661,"P20":1529},
 "wind":{"W_CAUTION":21.6,"activations":2,"bindings":0},
 "rainfall":{"sea_gt20":21,"sea_gt10":113,"kappa_1":0},
 "stop_conditions":{"canonical_output_conflict":False,"new_empirical_decision_required":False,
   "unexpected_empirical_drift":False,"protected_authority_change":False},
 "files_changed":["docs/canonical/empirical-findings-2026-09-06.md"],
 "all_clear":True}
(HERE/"reportable-figure-closure-verification.json").write_text(json.dumps(ver,indent=2)+"\n")
rep={}
for p in sorted(HERE.glob("*.csv")):
    raw=p.read_text(encoding="utf-8"); rdr=csv.reader(io.StringIO(raw)); hdr=next(rdr); n=len(hdr)
    bad=[(i+2,len(r)) for i,r in enumerate(rdr) if len(r)!=n]
    dr=len(list(csv.DictReader(io.StringIO(raw)))); df=pd.read_csv(io.StringIO(raw))
    rep[p.name]={"fields":n,"dictreader_rows":dr,"pandas_rows":int(df.shape[0]),"malformed":bad,
      "parse":"PASS" if not bad and dr==df.shape[0] and n==df.shape[1] else "FAIL"}
(HERE/"parser-test.json").write_text(json.dumps(rep,indent=2)+"\n")
for k,v in rep.items(): print("%-5s %-44s fields=%2d DictReader=%2d pandas=%2d"%(v["parse"],k,v["fields"],v["dictreader_rows"],v["pandas_rows"]))
print("ALL PASS:",all(v["parse"]=="PASS" for v in rep.values()))
print("classification:",dict(collections.Counter(r[5] for r in rows)))
